import turtle

radius = eval(input("Enter the radius: "))

turtle.setup(1000, 1000)
t1 = turtle.Turtle()
t1.pensize(5)
t1.penup()
t1.goto(-radius, 0)
t1.pendown()
t1.circle(radius)
t1.penup()
t1.goto(-radius, -2 * radius)
t1.pendown()
t1.circle(radius)
t1.penup()
t1.goto(radius, 0)
t1.pendown()
t1.circle(radius)
t1.penup()
t1.goto(radius, -2 * radius)
t1.pendown()
t1.circle(radius)
t1.hideturtle()
turtle.done()